### ISSUE TITLE
Non-Free Network Services

### ISSUE THREAD

**Issue by akademy** [sapstern/newshourpodcasts#3]
On FDroid this says "Non-Free Network Services" but The BBC world service is free.

Think it's unfair to flag this.

**Comment by sapstern** [comment]
Hi Mathew,

thanks for your feedback.

I tried hard ho get rid of this, to no avail so far.

This brings up the even more basic question, of the setup of F-Droid 
organization.

E.g.. There seems to be no arbitration panel, or something alike.

Best

Matthias

**Comment by sapstern** [comment]
I have had an ugly forum argument on F-Droid (guys full of self importance) which made me decide to withdraw from that place.
https://forum.f-droid.org/t/f-droid-arbitration-panel-antifeatures-how-are-they-decided/22325
